baseurl: "www.evovanialeonard.co.za"

title      : evo Vania Leonard   |    Bond Origination and Home Loan Expert
email      : vania.leonard@evogroup.co.za
description: A seasoned property professional with 28 years of experience in many aspects of the property industry from sales to finance. Specialisnig in bond finance and origination, I am committed to excellent client service, building long-term relationships and always focus on the client's best interests rather than my own personal gain.
author     : Eben Roux / Pieter Oosthuizen

analytics:
  google: 

collections:
  portfolio:

markdown: kramdown

webserver_headers:
  - - Access-Control-Allow-Origin
    - "*"
  - - Access-Control-Allow-Methods
    - GET, OPTIONS, HEAD

logo:
  path: /assets/logo.png

exclude: [node_modules,webpack-config.js,package.json,package-lock.json]